import '../../features/products/data/models/product_model.dart';

List<Product> demoProducts(String adminId) {
  final now = DateTime.now();
  return [
    Product(
      id: '',
      name: 'Yaourt nature',
      brand: 'Bio Fresh',
      barcode: '1234567890123',
      qrCodeValue: null,
      category: 'Produits laitiers',
      calories: 95,
      proteins: 5.2,
      carbs: 7.5,
      fats: 3.2,
      ingredients: 'Lait, ferments',
      allergens: 'Lait',
      extraNutrients: const [],
      imageUrl: null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    ),
    Product(
      id: '',
      name: 'Barre cereales',
      brand: 'NutriBar',
      barcode: '7894561230123',
      qrCodeValue: null,
      category: 'Cereales',
      calories: 180,
      proteins: 4.1,
      carbs: 28.0,
      fats: 6.2,
      ingredients: 'Flocons, miel, fruits secs',
      allergens: 'Fruits a coque',
      extraNutrients: const [],
      imageUrl: null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    ),
    Product(
      id: '',
      name: 'Eau minerale',
      brand: 'Atlas',
      barcode: '6541237894567',
      qrCodeValue: null,
      category: 'Boissons',
      calories: 0,
      proteins: 0,
      carbs: 0,
      fats: 0,
      ingredients: 'Eau',
      allergens: '',
      extraNutrients: const [],
      imageUrl: null,
      isActive: true,
      createdAt: now,
      updatedAt: now,
      createdBy: adminId,
    ),
  ];
}
